### PR TITLE
docs: mention catppuccin is now upstreamed

### LINKED ISSUE #9: Convert from YAML to KDL
Zellij  now uses kdl format and abandoned yaml.

The command `zellij convert-theme [yaml filepath] > [new kdl filepath]` will do the trick.

### PR DESCRIPTION
**Pull request by jaeheonji**
Hi! [zellij v0.32.0](https://github.com/zellij-org/zellij/releases/tag/v0.32.0) has been released 🚀
There are BREAKING CHANGES in this version.

Now, zellij uses [kdl](https://kdl.dev/) from yaml for all config files.
So, I changed the theme to fit the format of `KDL`. 

But, there seems to be one bug with the theme system in the new version. So I will draft this PR until the bug is fixed.

### CODE REVIEW

**Comment by sgoudham** [comment]
Hey 👋 @jaeheonji, nice work on all this and thanks for being so quick on the ball with zellij's new release. 

Just one comment from me: Would it not be better to have the YAML as the lovely people over at zellij have ensured that it's backwards compatible? 

Of course, the file itself isn't too complex to migrate but I'm wondering your thoughts are on potentially keeping both the existing `.yaml` and the new `.kdl` within the repository? Or even just keeping the `.yaml` as it will still work on the newer version?

Thanks again for keeping this port up to date! ❤️

**Comment by jaeheonji** [comment]
@sgoudham Thanks for your comments. I fully understand your opinion.
But, the zellij community has decided to only support KDL after this release.

Instead, zellij supports its own `yaml` to `kdl` migration tool. 
If the user uses the existing yaml configuration file, zellij automatically converts the file into KDL format with a guide.

Of course, `yaml` is very popular and friendly. And some people may disagree with this decision.

However, this decision could give zellij a more scalable configuration in the future. So I would really appreciate it if you could understand.

**Comment by sgoudham** [comment]
Yeah of course! I was just curious about your thoughts behind it. I guess if people really wanted the `.yaml`, they could go back in the commit history!

One of the main maintainers behind zellij is a huge fan of catppuccin so I'm really glad we have support for them! Thanks again! ❤️

**Comment by jaeheonji** [comment]
Sorry I'm late! A new version ([zellij v0.33.0](https://github.com/zellij-org/zellij/releases/tag/v0.33.0)) was released yesterday with the bug fixed.
Now it is ready to be merged :)

**Comment by sgoudham** [comment]
I was scrolling through the zellij repository when I realised that they have themes included in the repository itself [here](https://github.com/zellij-org/zellij/tree/main/example/themes) 

I think it would be _really neat_ if we could upstream all this work so that it's more visible over there. Also, we could post our screenshots in their [Theme Gallery](https://zellij.dev/documentation/theme-gallery.html) section in the documentation. 

What do you think? @jaeheonji

**Comment by jaeheonji** [comment]
@sgoudham Thank you for your opinion. I think that's a really good way too.
If the catppuccin community wants it, I'm willing to go ahead with it.

But in that case, how will this repository be managed in the future?

**Comment by jaeheonji** [comment]
Hey, I've updated this to the official documentation :)
https://zellij.dev/documentation/theme-gallery.html#catppuccin-mocha

And added a small fix.

**Comment by sgoudham** [comment]
Sorry, this PR went out of my mind for a while! @jaeheonji 

Do we want to update the README on this repository to indicate that this theme is now upstreamed in Zellij itself? Prior art would be [WezTerm's README](https://github.com/catppuccin/wezterm)

**Comment by jaeheonji** [comment]
Hi, @sgoudham. It's okay.

I added the link about zellij theme gallery. so now users will be able to find that zellij itself provides themes.
Please let me know if there is anything that needs to be corrected.

**Comment by sgoudham** [comment]
The link to the theme gallery looks good. However, I thought upstreaming the theme meant that you don't need to manually copy the files anymore and simply just set `theme: catppuccin-mocha` ?

If that's the case, we should modify the usage section to highlight that the manual method is not needed anymore? @jaeheonji

**Comment by jaeheonji** [comment]
> I thought upstreaming the theme meant that you don't need to manually copy the files anymore and simply just set theme: catppuccin-mocha ?

I guess I didn't understand. actually,  zelllij does not include theme file now.
So, to set the theme, the user must download the specific file locally.

**Comment by sgoudham** [comment]
Ah right, I was under the impression that the user did not need to manually download anything if it was included in the zellij repository. That's my bad, apologies. 

Do you know if Zellij would support including the example themes upon installation? Just wondering as we now effectively have 2 places to maintain the theme and it would be nice if the source of truth for the theme was just in the Zellij repository.

Again, apologies for not fully understanding what upstreaming really meant for Zellij.

**Comment by jaeheonji** [comment]
I'm fine 😄 I also misunderstood things. 

> Do you know if Zellij would support including the example themes upon installation? Just wondering as we now effectively have 2 places to maintain the theme and it would be nice if the source of truth for the theme was just in the Zellij repository.

Unfortunately, currently zellij does not have that feature like a `wezterm` and `helix`. However, I fully feel the need for the feature, so it is included in the milestone.

**Comment by sgoudham** [comment]
Gotcha. For now, I think we should match the "upstreamed" theme in this repo and just wait till themes are *hopefully* included within Zellij itself and then we can update the README to reflect that?

**Comment by jaeheonji** [comment]
Yes, for now, that seems the best way. Then I will not update the README file for now. right?

**Comment by sgoudham** [comment]
Edit: Discussed on discord and I think it would be best to merge so that the .kdl files are the same in both repositories and update the README at a later date when the theme directory is bundled

Thanks again for taking that on ❤️

**Comment by sgoudham** [comment]
Hey @jaeheonji, thanks for your work on the plugin system! I see that it's now bundled with Zellij itself and think it would be good to merge this PR in.

However, I tried searching for `catppuccin` in the Zellij [theme gallery](https://zellij.dev/documentation/theme-gallery.html) and I'm not able to find it anymore. Is it now in a different place?

**Comment by jaeheonji** [comment]
@sgoudham You are welcome! and Thank you for your patience!

> I see that it's now bundled with Zellij itself and think it would be good to merge this PR in.

Yes! but, there are currently a few issues and a hotfix is ​​coming soon. So, when everything is resolved, I'll let you know again!

> However, I tried searching for catppuccin in the Zellij [theme gallery](https://zellij.dev/documentation/theme-gallery.html) and I'm not able to find it anymore. Is it now in a different place?

Oh, I didn't know that. But don't worry. Perhaps that part is missing from the recent update of all documentation. I will also update it again when new hotfixes come out.

**Comment by jaeheonji** [comment]
@sgoudham Sorry for late! 

From version [zellij v0.37.2](https://github.com/zellij-org/zellij/releases/tag/v0.37.2), we successfully provide basic themes including Catppuccin.

And I also updated the documentation again. [theme-gallery](https://zellij.dev/documentation/theme-gallery.html)

It's been a very long time, and now it seems we are finally ready to update this PR 😄

**Comment by sgoudham** [comment]
@jaeheonji Thanks for that! 

I think we should remove the code from this repository entirely and just update the README on how to use the theme via zellij and link off to the theme gallery!

**Review by sgoudham — APPROVED** [review]

**Comment by sgoudham** [comment]
I'll go ahead and merge this as I don't think we can refactor it anymore. 
Thank you for all your work!! @jaeheonji

**Pull request merged**
