### PR TITLE
feat: add new way to set theme

### PR DESCRIPTION
**Pull request by jaeheonji**
Hi! First of all, thank you for creating a catppuccin theme for zellij.

A new version of zellij was released a few days ago. This version adds very cool features for setting themes.
* https://github.com/zellij-org/zellij/pull/1577
* https://github.com/zellij-org/zellij/pull/1536

Actually, I am making this PR to introduce this wonderful news.

So I made 4 themes as a test, but I'm not sure if this fits the rules of the catppuccin community.
If you plan to update yourself, I hope this PR is helpful.

### CODE REVIEW

**Comment by mainrs** [comment]
Thanks for the PR @jaeheonji. Did you test the themes out to make sure they work? If so I'd happily merge.

Closes #1.

**Comment by jaeheonji** [comment]
I tested it like this:

**Latte**
latte

**frappe**
frappe

**macchiato**
macchiato

**mocha**
mocha

In the case of latte, it is a bright color, so I updated colors. (I referenced the wezterm color layout)

**Comment by nekowinston** [comment]
LGTM

Awesome.

**Comment by mainrs** [comment]
The light theme looks good. I probably need to switch to it at some point! Thanks for getting this merged!

**Comment by mainrs** [comment]
@jaeheonji Feel free to add yourself to the "Thanks to" section in the readme file if you want to! Thanks for the help!

**Pull request merged**
